### ISSUE TITLE
feedback on JOSS paper text

### ISSUE THREAD

**Issue by sblunt** [darthoctopus/reggae#12]
Hey folks! I've given your JOSS text a close read, and I have a few suggestions based on the checkbox items of the JOSS review process. I'm a total astroseismology noob, so please forgive my ignorance! 

Summary: 

1. It was a little unclear to me upon first few reads where `PBJam` and `reggae` overlap (and don't) in functionality. I think that can be clarified a bit in the summary and statement of need. Is it correct to state that `PBJam` performs full fits, while `reggae` visualizes them and performs small fits to reduce prior search volume?

2. "We are building a prior sample distribution of asymptotic parameters for these dipole modes" -- as an outsider to the field, I have no idea what this means. Are you constraining the population of asymptotic parameters for dipole modes across all stars, one star, a subset of stars? How do you expect knowledge will be used by the community?

3.  In the first paragraph of the statement of need, I think it would be helpful to add a reference the reader can refer to for more info/examples about period-echelle power diagrams and why they are more helpful than traditional echelle diagrams for mixed-mode oscillators. I felt that I had to do a lot of digging to get the background info I needed to understand this section. Also, the way you correct for mixed-mode coupling is described in the next section, right? It may help to just include a parenthetical "see next section" when you introduce the correction.

4. "reggae picks up where pbjam leaves off" -- this sentence confused me. Maybe something like "reggae visualizes the residuals to an l=0,2 model computed by PBJam, and can either be used to visualize or manually tune an initial guess for the l=1 mode"

5. I don't think you discussed "state of the field" anywhere in the JOSS text. Could you add a short section summarizing similar software, or saying something like "we're not aware of other software for visualizing dipole mode fits."

A few other documentation suggestions:

1. In your code of conduct, please add an email address where it says [INSERT EMAIL ADDRESS]

2. I agree with @sybreton's most recent comment about expanding the sample usage. In particular, I think it would be helpful to walk the user through generating the figure you show in the JOSS paper.

3. Have you gotten your readthedocs page working? I see that you've got sphinx documentation, and I can see reggae on readthedocs when I google it, but when I click the link, I get a 404 error. Once you get the docs up and running, I'd suggest linking to them from your readme page too.

https://github.com/openjournals/joss-reviews/issues/6588

**Comment by darthoctopus** [comment]
Hi Sarah,

Thanks for the constructive suggestions, and much-needed outside perspective! I will work on addressing your major points about the paper per se later this evening, but for now, I think we have managed to address your minor points. You may have seen some of these in our response to @sybreton, but, for completeness:
- I have added both my and Martin's email addresses to the Code of Conduct
- We now have a (hopefully sufficiently detailed) Quick Start guide containing a rough outline of the steps we followed to produce fits to the power spectrum like the one provided in the test case
- We've managed to get our documentation hosted at <https://pb-reggae.readthedocs.io/>, since the `reggae` short name was already taken by an unrelated project.

**Comment by darthoctopus** [comment]
Hi Sarah,

I have updated the JOSS paper (in the paper-specific branch) to hopefully address your comments. In particular:

1. We now (hopefully) make clear that, whereas pbjam is intended for fitting individual mode frequencies, reggae is intended instead to assist in visual assessment of, and deriving preliminary constraints on, the overall properties of the dipole modes (e.g. characteristic spacings, rotation rates, phase offsets instead of individual frequencies).
2. The phrasing for this sentence is now "`PBjam` 2 will specify prior distributions on these parameters empirically, through predetermined values found for existing samples of solar-like oscillators." --- this better reflects how this population of parameters, as determined from primarily Kepler and TESS, will be applied to PLATO data.
3. Since this level of technical detail doesn't seem to be necessary in a statement of need, and (as you observe) is already provided in the subsequent sections, we have simplified this passage significantly, and added references to each application described here.
4. This sentence has been revised to hopefully be more immediately descriptive of what reggae actually does.
5. We've added some words to this effect to the statement of need: "no other tools currently exist for performing this task in the nonasymptotic parameterisation that PBjam will use"

The revised manuscript is unfortunately a little longer than the 1000 word limit, however.

**Comment by sybreton** [comment]
Hi Sarah and Joel,

Concerning the paper, I just have a few minor comments so I think it is better I send them here rather than opening another issue:

"_PBjam [@{2021AJ....161...62N}] is a software instrument for fitting solar-like oscillation modes ("peakbagging")_"
--> concerning solar-like oscillations maybe add a reference towards a recent general review of the field, e.g. García & Ballot 2019 (https://ui.adsabs.harvard.edu/abs/2019LRSP...16....4G/abstract)

"_Since the primary samples of the PLATO mission consist mainly of main-sequence and subgiant stars [@plato], PBjam implements a parameterisation of dipole mixed-mode frequencies --- as described by their overtone spacings, boundary conditions, and other stellar properties --- that is suitable to these stars_"
--> it is ambiguous that mixed modes are expected only for subgiant and not for main-sequence stars, I think this sentence should be slightly rephrased to avoid any confusion on this aspect. 

"_the nonasymptotic construction_" 
--> for clarity towards non-specialists, it would be good to recall at this point that the non-asymptotic regime corresponds to subgiant stars. 

How far are you currently from the 1000 words limit ?

**Comment by darthoctopus** [comment]
Hi Sylvain,

Thanks for these notes. I've made the following changes to the draft:

1. The first sentence now reads "`PBjam` is a software instrument for fitting normal modes ("peakbagging\") in power spectra from space-based photometry of solar-like oscillators [e.g. @garcia_asteroseismology_2019]" , incorporating your suggested reference.
2. The phrasing of this sentence has been changed from "suitable to these stars" to "reduces to pure p-modes in the former, and is suitable to the latter".
3. This sentence is now rephrased to read "the nonasymptotic construction for subgiants here".

Presently the manuscript (including author metadata but not references) is 1080 words long.
